In [55]:
import numpy as np

A = np.array([np.array([1,2,5]), np.array([3,4,10]), np.array([2,9,4])])
print(A)
# print(A[0][0])

def minor(A, i, j):
    M = []

    new_row = []
    c_index = 0
    r_index = 0

    for r in A:
        for entry in r:
            if c_index != j and r_index != i:
                new_row += [entry]
            c_index += 1
        
        c_index = 0
        r_index += 1

        M.append(np.array(new_row))
        new_row = []
    print(M)
    return print(np.array(M))


def det(A):
    if len(A[0]) < 3:
        return A[0][0]*A[1][1] - A[0][1]*A[1][0]
    else:
        n = len(A) + len(A[0])
        return A[0,0] + n * det()

minor(A,0,0)

[[ 1  2  5]
 [ 3  4 10]
 [ 2  9  4]]
[array([], dtype=float64), array([ 4, 10]), array([9, 4])]


ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (3,) + inhomogeneous part.

In [41]:
K = np.array([])
np.append(K, ["24"])
print(K)

[]
